### ISSUE TITLE
Inloggad som?

### ISSUE THREAD

**Issue by jh222xk** [juhaniaa/ja222qm-webbramverk-a#1]
Man ser inte vem man är inloggad som. Det står bara: `Du är nu inloggad`.

Skulle vara trevligt att se.

**Comment by SheriefBadran** [comment]
Det enda jag ser när jag loggar in är Show, där skulle det vara bra om du skrev ut mitt användarnamn/epost. Gärna också bekräftelse på att nyckeln är borttagen/genererad.

**Comment by juhaniaa** [comment]
Det hade jag glömt att fixa, "Show" fanns där för testningssyfte i början. Tack.
