### ISSUE TITLE
Konsekvent kod

### ISSUE THREAD

**Issue by jh222xk** [juhaniaa/ja222qm-webbramverk-a#10]
Du är inte konsekvent i din kod, din variabel som innehåller user är olika överallt:  `u`, `@user`, `@Users`

https://github.com/juhaniaa/ja222qm-webbramverk-a/blob/master/app/controllers/admins_controller.rb#L11

https://github.com/juhaniaa/ja222qm-webbramverk-a/blob/master/app/controllers/admins_controller.rb#L16

https://github.com/juhaniaa/ja222qm-webbramverk-a/blob/master/app/controllers/users_controller.rb#L6

https://github.com/juhaniaa/ja222qm-webbramverk-a/blob/master/app/controllers/users_controller.rb#L18

Tycker du skulle ha samma så blir det lite tydligare men är helt klart en smaksak, om man ska vara riktigt petig så använder ruby-communityn inte camelCase:

https://github.com/juhaniaa/ja222qm-webbramverk-a/blob/master/app/controllers/admins_controller.rb#L23

utan istället underscore (_):

https://github.com/juhaniaa/ja222qm-webbramverk-a/blob/master/app/controllers/users_controller.rb#L75

Men också smaksak som sagt och det är petitesser.

**Comment by juhaniaa** [comment]
Har fixat detta, beror nog lite på att jag inte än har förstått skillnaden mellan u och @u. Men tack för all input och hjälp :)

**Comment by jh222xk** [comment]
Kanon! Som sagt bara lite tips på hur man kan göra om man vill vara väldigt petig :P
