### ISSUE TITLE
Applikationen

### ISSUE THREAD

**Issue by SheriefBadran** [juhaniaa/ja222qm-webbramverk-a#12]
Generellt upplever jag att du gjort minsta möjliga. Applikationen har ingen styling alls och det saknas responsmeddelanden och delar i gränssnittet som talar om för användaren vart man befinner sig. Rubriken “Show” visas när jag loggat in för att se min nyckel. Show låter som en metod och inte en rubrik.

**Comment by juhaniaa** [comment]
Har fixat rubriken så att den säger "Profil" och välkomnar användaren. Håller med om minsta möjliga, jag upptäckte väl lite att jag kunde göra registreringsapplikationen i samma som webb-apiet för labb 2 så jag tror jag kommer göra om registreringen där och har därför inte gett denna så mycket kärlek.
