### ISSUE TITLE
Login, Registrering och Admin

### ISSUE THREAD

**Issue by SheriefBadran** [juhaniaa/ja222qm-webbramverk-a#13]
## Login

Fungerar bra!

Ett tips är att kolla så att lösenordet inte får vara hur kort som helst. Jag kunde både registrera mig och logga in med ett tecken i lösenordet.
## Registrering

Fungerar bra, förutom problemet som näms under Login.
## Admin

Admin fungerar bra!

**Comment by juhaniaa** [comment]
Fixat tack för påminnelsen
