### ISSUE TITLE
Kod

### ISSUE THREAD

**Issue by SheriefBadran** [juhaniaa/ja222qm-webbramverk-a#14]
Applikationen och gränssnittet gav ett blekt intryck, däremot gillar jag din kod/kodstil. Det är väldigt tydligt vad som händer. Exempelvis gillar jag att du valt att använda alternativ 
syntax som:
@current_user ||= User.find(session[:userid]) **if session[:userid]**

I klassen User validerar du saker som har med email att göra, ett tips är att även validera med
**validates :password, length: {minimum: 8}** för att lösa problemet med för korta lösenord.

Jag tycker att du satt upp dina routes på ett bra sätt.

**Comment by juhaniaa** [comment]
Fixade lösenordet utifrån tidigare issue så det blev 5 tecken. Tack för input och hjälp.
