### ISSUE TITLE
Inloggning admin

### ISSUE THREAD

**Issue by SheriefBadran** [juhaniaa/ja222qm-webbramverk-a#4]
Jag kanske är blind, men ser inte inloggningsuppgifter till admin??

**Comment by jh222xk** [comment]
@SheriefBadran https://github.com/juhaniaa/ja222qm-webbramverk-a/#ja222qm-webbramverk-a

`Admin login at /admin username: admin password: admin`

**Comment by SheriefBadran** [comment]
Ok nu ser jag, missade att inloggning ligger på /admin.
