### ISSUE TITLE
Blandning av slim-templates och ERB-templates

### ISSUE THREAD

**Issue by jh222xk** [juhaniaa/ja222qm-webbramverk-a#6]
Du har en del "slim-templates" här:

https://github.com/juhaniaa/ja222qm-webbramverk-a/tree/master/app/views/errors

och sedan har du rails default templates (erb) här:

https://github.com/juhaniaa/ja222qm-webbramverk-a/tree/master/app/views/users

och på andra ställen men sen har du mixat här:

https://github.com/juhaniaa/ja222qm-webbramverk-a/tree/master/app/views/layouts

Håll dig till en sort of template-engine istället.

**Comment by juhaniaa** [comment]
Dessa är en del av experiment/labbande utifrån olika google-sökningar och används inte i applikationen. Jag borde antagligen ha tagit bort dem inför releasen.
