### ISSUE TITLE
Errorhantering

### ISSUE THREAD

**Issue by jh222xk** [juhaniaa/ja222qm-webbramverk-a#7]
Varför har du skrivit en egen "error handler"?

https://github.com/juhaniaa/ja222qm-webbramverk-a/blob/master/app/controllers/errors_controller.rb

Jag får inga som helst fel i utvecklingsmiljön. Man ska inte behöva skriva egna "error handlers" om man inte har något speciellt användingsfall, rails sköter detta beroende på vilket värde du har i en environment variable som heter RAILS_ENV. Om RAILS_ENV='production' så visas inga fel för klienten, dem loggas istället, vid RAILS_ENV='developement' vill vi ha _alla_ fel.

https://github.com/juhaniaa/ja222qm-webbramverk-a/tree/master/config/environments

**Comment by juhaniaa** [comment]
Dessa är en del av experiment/labbande utifrån olika google-sökningar och används inte i applikationen. Jag borde antagligen ha tagit bort dem inför releasen.

**Comment by jh222xk** [comment]
Okej, för jag fick inte fram några som helst fel (när jag gjorde så jag fick fel med mening, inget fel på din kod).

Så det känns som att den användes?
